ignore:
 - "snail-kotlin/src/main/java/com/compass/snail/extensions"
 - "snail-kotlin/src/test"
coverage:
  status:
    patch: no
    project:
      default:
        against: parent
        target: auto
